export const RESET_PRODUCTS = "RESET_PRODUCTS";
export const SHOW_PROMOTED = "SHOW_PROMOTED";
export const SORT_BY_PRICE_UP = "SORT_BY_PRICE_UP";
export const SORT_BY_PRICE_DOWN = "SORT_BY_PRICE_DOWN";
export const INPUT_CHANGE = "INPUT_CHANGE";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
